/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsLoginRouteImport } from './routes/applications/login'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs/$programId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsLoginRoute = ApplicationsLoginRouteImport.update({
  id: '/applications/login',
  path: '/applications/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/programs/$programId/',
  path: '/programs/$programId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications/login': typeof ApplicationsLoginRoute
  '/applications': typeof ApplicationsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications/login': typeof ApplicationsLoginRoute
  '/applications': typeof ApplicationsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications/login': typeof ApplicationsLoginRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications/login'
    | '/applications'
    | '/programs'
    | '/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications/login'
    | '/applications'
    | '/programs'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/applications/login'
    | '/applications/'
    | '/programs/'
    | '/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsLoginRoute: typeof ApplicationsLoginRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/login': {
      id: '/applications/login'
      path: '/applications/login'
      fullPath: '/applications/login'
      preLoaderRoute: typeof ApplicationsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsLoginRoute: ApplicationsLoginRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
